## changed at Sun Feb 22 17:29:27 MSK 2026
#Sun Feb 22 17:29:27 MSK 2026
com.dtl.jetbrains.utils.IdeaSlowOperationsAssertionUtils.isUnreadDefault=false
com.dtl.jetbrains.utils.IdeaSlowOperationsAssertionUtils.defaultValue=false
